version: '3.8'
services:
  remote-dropid:
    image: urielch/remote-droid:latest
    privileged: true
    devices:
      - '/dev/bus/usb:/dev/bus/usb'
    ports:
      - 3009:3009
    networks:
      - remote-droid
    environment:
      GLOBAL_PREFIX: '/remote/local'
