version: '3.8'
services:
  remote-dropid:
    image: urielch/remote-droid:0.1.11
    privileged: true
    devices:
      - '/dev/bus/usb:/dev/bus/usb'
    ports:
      - 3009:3009
    restart: always
    environment:
      GLOBAL_PREFIX: '/remote/local'
      JWT_SECRET: 'disabled'
